variables:
  GIT_SUBMODULE_STRATEGY: recursive

debian/9/amd64:
  image: datamove/debian/9/amd64
  tags:
    - lxd
  script:
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. ~/PDAF-D_V1.15 ~/fti
