variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_deps
  - build
  - test

build_deps:
  type: build
  tags:
    - linux
  script:
    # Do not build zmq if it is already installed by the system to speed up run
    - "mkdir melissa/build && cd melissa/build && cmake .. && make"
  artifacts:
    paths:
      - melissa/install/

build:
  type: build
  tags:
    - linux
  script:
    # Do not build zmq if it is already installed by the system to speed up run
    - "mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install && make -j 10"
  artifacts:
    paths:
      - build/
  dependencies:
    - build_melissa

test:
  type: test
  tags:
    - linux
  script:
    - "cd build && ctest --verbose"
  dependencies:
    - build


