variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_deps
  - build
  - test

build_deps:
  stage: build_deps
  tags:
    - melissa-da
  script:
    # Do not build zmq if it is already installed by the system to speed up run
    - "mkdir melissa/build && cd melissa/build && cmake .. && make"
    - ls -la
    - find . -type d -iname "install"
    - find . -type d -iname "build"
  artifacts:
    paths:
      - install/

build:
  stage: build
  tags:
    - melissa-da
  script:
    # Do not build zmq if it is already installed by the system to speed up run
    - "mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install && make -j 10"
  artifacts:
    paths:
      - build/
  dependencies:
    - build_deps

test:
  stage: test
  tags:
    - melissa-da
  script:
    - "cd build && ctest --verbose"
  dependencies:
    - build


